import os
from building import *

cwd = GetCurrentDir()

list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        SConscript(os.path.join(d, 'SConscript'))
