import os
from building import *

cwd = GetCurrentDir()

Import('asenv')
ASROOT = asenv['ASROOT']

download = '%s/release/download'%(ASROOT)
fatfs='%s/ff13'%(download)

objs = []

if(not os.path.exists(fatfs)):
    MKDir(download)
    try:
        RunCommand('''cd %s && wget http://elm-chan.org/fsw/ff/arc/ff13.zip && 
        mkdir ff13 && cd ff13 && unzip ../ff13.zip && rm source/diskio.c'''%(download))
        cmd = 'sed -i "138c #define FF_FS_RPATH        2" ffconf.h'
        cmd += ' && sed -i "41c #define FF_USE_MKFS        1" ffconf.h'
        RunCommand('cd %s/ff13/source && %s'%(download,cmd))
    except:
        Return('objs')

MKSymlink(fatfs,'%s/fatfs'%(cwd))

objs += Glob('fatfs/source/*.c')

asenv.Append(CCFLAGS = '-I%s/fatfs/source'%(cwd))
asenv.Append(CCFLAGS = '-DUSE_FATFS')

Return('objs')
