/*
* Configuration of module: Can
*
* Created by:   parai          
* Copyright:    (C)parai@foxmail.com  
*
* Configured for (MCU):    MinGW ...
*
* Module vendor:           ArcCore
* Generator version:       2.0.34
*
* Generated by easySAR Studio (https://github.com/parai/OpenSAR)
*/
#include "Can.h"

static const Can_FilterMaskType vCanFilterMask0= 0xFFFFFFFF;

static const Can_HardwareObjectType CAN_CTRL_1_HOHCfgData[]=
{

    {    /* Can0Hrh */
        .CanHandleType=CAN_ARC_HANDLE_TYPE_BASIC,
        .CanIdType=CAN_ID_TYPE_STANDARD,
        .CanIdValue=0x00,/*TODO*/
        .CanObjectId=0,
        .CanObjectType=CAN_OBJECT_TYPE_RECEIVE,
        .CanFilterMaskRef=&vCanFilterMask0,/*TODO*/
        .Can_Arc_MbMask=0x00000000,/*TODO*/
        .Can_Arc_EOL=FALSE
    },

    {    /* Can0Hth */
        .CanHandleType=CAN_ARC_HANDLE_TYPE_BASIC,
        .CanIdType=CAN_ID_TYPE_STANDARD,
        .CanIdValue=0x00,/*TODO*/
        .CanObjectId=0,
        .CanObjectType=CAN_OBJECT_TYPE_TRANSMIT,
        .CanFilterMaskRef=&vCanFilterMask0,/*TODO*/
        .Can_Arc_MbMask=0x00000000,/*TODO*/
        .Can_Arc_EOL=FALSE
    },

    {
        .Can_Arc_EOL = TRUE,
    }
};

const Can_ControllerConfigType  Can_ControllerCfgData[]=
{

    {
        .CanControllerId=CAN_CTRL_1,
        .CanRxProcessing=CAN_ARC_PROCESS_TYPE_INTERRUPT,
        .CanTxProcessing=CAN_ARC_PROCESS_TYPE_INTERRUPT,
        .CanWakeupProcessing=CAN_ARC_PROCESS_TYPE_INTERRUPT,
        .CanBusOffProcessing=CAN_ARC_PROCESS_TYPE_INTERRUPT,
        .CanControllerBaudRate=500,
        .Can_Arc_Hoh=CAN_CTRL_1_HOHCfgData,
        .Can_Arc_Loopback=FALSE
    }
    
};
extern void CanIf_RxIndication(uint8 Hrh, Can_IdType CanId, uint8 CanDlc,const uint8 *CanSduPtr);
extern void CanIf_TxConfirmation(PduIdType canTxPduId);
const Can_CallbackType CanCallbackConfigData = {
     NULL, //CanIf_CancelTxConfirmation,
     CanIf_RxIndication,
     NULL,//CanIf_ControllerBusOff,
     CanIf_TxConfirmation,
     NULL, //CanIf_ControllerWakeup,
     NULL //CanIf_Arc_Error,
 };
const Can_ConfigSetType Can_ConfigSetData ={Can_ControllerCfgData,&CanCallbackConfigData};
const Can_ConfigType CanConfigData ={&Can_ConfigSetData};

