import os
from building import *

cwd = GetCurrentDir()

Import('asenv')
MODULES = asenv['MODULES']

objs = []

if('CANIF' in MODULES):
    objs += Glob('CanIf/*.c')
    objs += Glob('CanIf/*.xml')
    asenv.Append(CCFLAGS='-DUSE_CANIF')

if('CANNM' in MODULES):
    objs += Glob('CanNm/*.c')
    asenv.Append(CCFLAGS='-DUSE_CANNM')

if('CANSM' in MODULES):
    objs += Glob('CanSM/*.c')
    asenv.Append(CCFLAGS='-I%s/CanSM'%(cwd))
    asenv.Append(CCFLAGS='-DUSE_CANSM')

if('CANTP' in MODULES):
    objs += Glob('CanTp/*.c')
    asenv.Append(CCFLAGS='-I%s/CanTp'%(cwd))
    asenv.Append(CCFLAGS='-DUSE_CANTP')

if('COM' in MODULES):
    objs += Glob('Com/*.c')
    asenv.Append(CCFLAGS='-I%s/Com'%(cwd))
    asenv.Append(CCFLAGS='-DUSE_COM')

if('COMM' in MODULES):
    objs += Glob('ComM/*.c')
    asenv.Append(CCFLAGS='-I%s/ComM'%(cwd))
    asenv.Append(CCFLAGS='-DUSE_COMM')

if('DOIP' in MODULES):
    objs += Glob('DoIP/*.c')
    asenv.Append(CCFLAGS='-I%s/DoIP'%(cwd))
    asenv.Append(CCFLAGS='-DUSE_DOIP')

if('NM' in MODULES):
    objs += Glob('Nm/*.c')
    asenv.Append(CCFLAGS='-I%s/Nm'%(cwd))
    asenv.Append(CCFLAGS='-DUSE_NM')

if('OSEKNM' in MODULES):
    objs += Glob('OsekNm/*.c')
    asenv.Append(CCFLAGS='-I%s/OsekNm'%(cwd))
    asenv.Append(CCFLAGS='-DUSE_OSEKNM')

if('PCI' in MODULES):
    objs += Glob('Pci/pci*.c')
    asenv.Append(CCFLAGS='-I%s/Pci'%(cwd))
    asenv.Append(CCFLAGS='-DUSE_PCI')
    if(os.name == 'nt'):
        asenv.Append(CCFLAGS='-DUSE_PCAPIF')

if('PDUR' in MODULES):
    objs += Glob('PduR/*.c')
    asenv.Append(CCFLAGS='-I%s/PduR'%(cwd))
    asenv.Append(CCFLAGS='-DUSE_PDUR')

if('RPMSG' in MODULES):
    objs += Glob('RPmsg/*.c')
    asenv.Append(CCFLAGS='-I%s/RPmsg'%(cwd))
    asenv.Append(CCFLAGS='-DUSE_RPMSG')

if('SOAD' in MODULES):
    objs += Glob('SoAd/*.c')
    asenv.Append(CCFLAGS='-I%s/SoAd'%(cwd))
    asenv.Append(CCFLAGS='-DUSE_SOAD')

if('XCP' in MODULES):
    objs += Glob('Xcp/*.c')
    asenv.Append(CCFLAGS='-I%s/Xcp'%(cwd))
    asenv.Append(CCFLAGS='-DUSE_XCP')

Return('objs')
