from building import *
Import('asenv')
ARCH=asenv['ARCH']
MODULES=asenv['MODULES']

cwd = GetCurrentDir()

objs = []

objs += SConscript('%s/SConscript'%(ARCH))

if('LWIP' in MODULES):
    objs += Glob('common/lwip/*.c')
    asenv.Append(CPPPATH=['%s/common/lwip'%(cwd)])

Return('objs')