import os

Import('BOARD')

cwd = os.path.abspath(os.curdir)
objs = []
list = os.listdir(cwd)

for d in list:
    if((d[:6] == 'board.') and (d[6:] != BOARD)):
        continue
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')