import os
from building import *

cwd = GetCurrentDir()

Import('asenv')
Import('ASROOT')

objs = []

objs += Glob('%s/../board.bcm2835/common/*.c'%(cwd))

asenv.Append(CCFLAGS=' -I%s/../board.bcm2835/common '%(cwd))

asenv.Append(CCFLAGS=' -DMEMORY_SIZE=0x8000000 ')
asenv.Append(CCFLAGS=' -DSYSTEM_REGION_START=0x10000000 ')
asenv.Append(CCFLAGS=' -DSYSTEM_REGION_END=0x101f4000 ')
asenv.Append(CCFLAGS=' -DPAGE_SIZE=0x1000 ')

#lds = '%s/../board.bcm2835/script/linker-app.lds'%(cwd)
lds = '%s/com/as.infrastructure/arch/bcm2835/bsp/linker.lds'%(ASROOT)
asenv.Append(LINKFLAGS=' -static -T %s '%(lds))
asenv.Append(LINKFLAGS='-Map build/versatilepb/versatilepb.map')

MODULES = ['ECUM','SCHM','MCU',
           'DET',
           'CAN','CANIF','PDUR','COM','COMM','CANTP','CANNM',
           'DCM','CANNM','CANSM','NM','OSEKNM','XCP',
           'SOAD','DOIP','LWIP','PCI',
           'FATFS','LWEXT4']
ARCH='versatilepb'
arch='arm'

Export('MODULES')
Export('ARCH')
Export('arch')

Return('objs')