import os
from building import *

cwd = GetCurrentDir()

Import('asenv')
MODULES = asenv['MODULES']

objs = []

if('IFX' in MODULES):
    objs += Glob('Ifx/*.c')

if('FDT' in MODULES):
    objs += SConscript('libfdt/SConscript')

Return('objs')
