from building import *

Import('asenv')
MODULES = asenv['MODULES']

cwd = GetCurrentDir()

objs = []

if(('LWIP' in MODULES) and ('RTTHREAD' not in MODULES)):
    objs += SConscript('lwip/SConscript')

if(('LWIP' in MODULES) and ('FTP' in MODULES) and ('RTTHREAD' not in MODULES)):
    objs += Glob('ftp/*.c')
    asenv.Append(CPPDEFINES = 'FTPD_DEBUG')
    asenv.Append(CPPPATH = ['%s/ftp'%(cwd)])


Return('objs')