import os
from building import *
import xcc

xcc.SetDefaultRTOS('smallos')

cwd = GetCurrentDir()

Import('asenv')
arch = asenv['arch']

asenv.Append(CCFLAGS='-I%s'%(cwd))
if(arch=='arm'):
    asenv.Append(CCFLAGS='-I%s/portable/posix'%(cwd))
else:
    asenv.Append(CCFLAGS='-I%s/portable/%s'%(cwd,arch))

objs = []

objs += Glob('*.c')
if(arch=='arm'):
    objs += Glob('../askar/portable/arm/startup.S')
else:
    objs += Glob('portable/%s/*.c'%(arch))
    objs += Glob('portable/%s/*.S'%(arch))

Return('objs')