import os
from building import *
import xcc

xcc.SetDefaultRTOS('smallos')

cwd = GetCurrentDir()

Import('asenv')
arch = asenv['arch']

asenv.Append(CPPPATH=['%s'%(cwd)])
if(arch=='arm'):
    asenv.Append(CPPPATH=['%s/portable/posix'%(cwd)])
else:
    asenv.Append(CPPPATH=['%s/portable/%s'%(cwd,arch)])

objs = []

objs += Glob('*.c')
if(arch=='arm'):
    objs += Glob('../askar/portable/arm/startup.S')
else:
    objs += Glob('portable/%s/*.c'%(arch))
    objs += Glob('portable/%s/*.S'%(arch))

Return('objs')