from building import *

Import('asenv')
MODULES = asenv['MODULES']

cwd = GetCurrentDir()

objs = []

if(('FATFS' in MODULES) and (asenv['RTOS'] != 'rtthread')):
    objs += SConscript('fatfs/SConscript')

if('LWEXT4' in MODULES):
    objs += SConscript('lwext4/SConscript')

if('VFS' in MODULES):
    objs += Glob('vfs/*.c')
    asenv.Append(CPPPATH =['%s/vfs'%(cwd)])
    asenv.Append(CPPDEFINES='USE_VFS')

Return('objs')
