import os
from building import *

cwd = GetCurrentDir()

Import('asenv')

assert(asenv['BOARD'] == 'posix')

objs = []

asenv.Append(CCFLAGS='-I%s'%(cwd))
asenv.Append(CCFLAGS='-I%s/rs232'%(cwd))
if(os.name == 'nt'):
    asenv.Append(CCFLAGS='-I%s/peak-can'%(cwd))
    MKSymlink('%s/../../cancasexl.access/vxlapi.h'%(cwd),'%s/vxlapi.h'%(cwd))
    MKSymlink('%s/../../cancasexl.access/xlLoadlib.cpp'%(cwd),'%s/xlLoadlib.c'%(cwd))
    asenv.Append(CCFLAGS=['-DDYNAMIC_XLDRIVER_DLL', '-DPOINTER_32='])

objs +=  Glob('*.c')
objs +=  Glob('rs232/*.c')

if(os.name == 'nt'):
    objs += Glob('peak-can/lib/win32/PCANBasic.lib')
    if(asenv.GetOption('clean')):
        RMFile('%s/socketwin_can_driver.exe'%(cwd))
    elif(not os.path.exists('%s/socketwin_can_driver.exe'%(cwd))):
        cmd = 'gcc %s/socketwin_can_driver.c -D__SOCKET_WIN_CAN_DRIVER__ -o %s/socketwin_can_driver.exe -lwsock32'%(cwd,cwd)
        RunCommand(cmd)

Return('objs')
