import os
from building import *

Import('asenv')
MODULES=asenv['MODULES']

assert(asenv['BOARD'] == 'posix')

objs = []

objs +=  SConscript('can/SConscript')

if('AWS' in MODULES):
    objs +=  SConscript('device/websock/SConscript')
    asenv.Append(CCFLAGS='-DUSE_AWS')

Return('objs')
