import os
from building import *

cwd = GetCurrentDir()

Import('asenv')
MODULES = asenv['MODULES']

objs = []

if('EA' in MODULES):
    objs += Glob('Ea/*.c')
    asenv.Append(CPPPATH=['%s/Ea'%(cwd)])
    asenv.Append(CPPDEFINES='USE_EA')

if('FEE' in MODULES):
    objs += Glob('Fee/*.c')
    asenv.Append(CPPDEFINES='USE_FEE')

if('MEMIF' in MODULES):
    objs += Glob('MemIf/*.c')
    asenv.Append(CPPDEFINES='USE_MEMIF')

if('NVM' in MODULES):
    objs += Glob('NvM/*.c')
    asenv.Append(CPPDEFINES='USE_NVM')

Return('objs')
