from building import *

cwd = GetCurrentDir()

Import('asenv')
Import('MODULES')

objs = []

objs += SConscript('kernel/SConscript')

if('ECUM' in MODULES):
    objs += Glob('EcuM/*.c')
    asenv.Append(CCFLAGS=' -I%s/EcuM -DUSE_ECUM '%(cwd))

if('SCHM' in MODULES):
    objs += Glob('SchM/*.c')
    asenv.Append(CCFLAGS=' -I%s/SchM -DUSE_SCHM '%(cwd))

objs += SConscript('net/SConscript')

Return('objs')