from building import *

cwd = GetCurrentDir()

Import('asenv')
MODULES = asenv['MODULES']

objs = []

objs += SConscript('kernel/SConscript')

if('ECUM' in MODULES):
    objs += Glob('EcuM/*.c')
    asenv.Append(CCFLAGS='-I%s/EcuM'%(cwd)) 
    asenv.Append(CCFLAGS='-DUSE_ECUM')

if('SCHM' in MODULES):
    objs += Glob('SchM/*.c')
    asenv.Append(CCFLAGS='-I%s/SchM -DUSE_SCHM'%(cwd))

objs += SConscript('net/SConscript')
objs += SConscript('fs/SConscript')

Return('objs')