
clean:
	@(cd asboot;make clean)
	@(cd ascore;make clean)
	@(cd aslua; make clean)
	
00:
	@(cd asboot;make 00)
	@(cd ascore;make 00)
	@(cd aslua; make 00)

91:
	@(cd asboot;make 91)
	@(cd ascore;make 91)
	@(cd aslua; make 91)
	
94:
	@(cd asboot;make 94)
	@(cd ascore;make 94)
	@(cd aslua; make 94)
	@(cd asboot/out;rm core.dll)

depc:
	@(cd asboot;make depc)
	@(cd ascore;make depc)
	@(cd aslua; make depc)

	