import os
from building import *
Import('asenv')

cwd = GetCurrentDir()
ASROOT = asenv['ASROOT']
cwd = GetCurrentDir()

uip='%s/release/download/contiki'%(ASROOT)

MKDir('%s/core'%(cwd))


MKSymlink('%s/core/net'%(uip),'%s/core/net'%(cwd))

asenv.Append(CPPPATH=['%s/include'%(cwd),cwd])

objs = []

objs += Glob('%s/core/lib/memb.c'%(uip))
objs += Glob('%s/core/lib/random.c'%(uip))
objs += Glob('core/net/ipv4/*.c')
objs += Glob('core/net/ip/*.c')

SrcRemove(objs, ['uip-over-mesh.c','slipdev.c','dhcpc.c'])
Return('objs')

