import os
from building import *

cwd = GetCurrentDir()

Import('asenv')

sgapp = os.getenv('SGAPP')
if(sgapp is None):
    try:
        sgapp = asenv['SGAPP']
    except KeyError:
        pass

if(sgapp is None):
    print('WARNING: using default SGAPP virtual_cluster!')
    sgapp = 'virtual_cluster'

doneFlag = '%s/SgRes/%s.done'%(cwd,sgapp)
if((not os.path.exists(doneFlag)) and (not asenv.GetOption('clean'))):
    RMDir('%s/SgRes'%(cwd))
    MKDir('%s/SgRes'%(cwd))
    RunCommand('cd %s && %s %s/com/as.tool/config.infrastructure.gui/Sg.py %s/%s/Sg.xml'%(cwd,asenv['python3'],asenv['ASROOT'],cwd,sgapp))
    MKFile(doneFlag)

if(asenv.GetOption('clean')):
    RMDir('%s/SgRes'%(cwd))

objs = []

objs +=  Glob('SgRes/*.c')
objs +=  Glob('%s/src/*.c'%(sgapp))

asenv.Append(CCFLAGS='-I%s/SgRes'%(cwd))

Return('objs')
