import os
from building import *

cwd = GetCurrentDir()

Import('asenv')
MODULES = asenv['MODULES']
asenv.Append(CPPPATH=[cwd])

objs = Glob('*.c')

if('ASKAR' in MODULES):
    objs += SConscript('askar/SConscript')
elif('SMALLOS' in MODULES):
    objs += SConscript('small/SConscript')
elif('RTTHREAD' in MODULES):
    objs += SConscript('rtthread/SConscript')
elif('ATK2_SC4' in MODULES):
    objs += SConscript('toppers-atk/atk2-sc4/SConscript')
elif('TRAMPOLINE' in MODULES):
    objs += SConscript('trampoline/SConscript')
elif('TOPPERS_OSEK' in MODULES):
    objs += SConscript('toppers_osek/SConscript')
else:
    assert(0)
Return('objs')
