import os
from building import *

cwd = GetCurrentDir()

Import('asenv')
MODULES = asenv['MODULES']

objs = []

if('DCM' in MODULES):
    objs += Glob('Dcm/*.c')
    asenv.Append(CPPPATH=['%s/Dcm'%(cwd)])

if('DEM' in MODULES):
    objs += Glob('Dem/*.c')

if('DET' in MODULES):
    objs += Glob('Det/*.c')

Return('objs')
