import os
from building import *

cwd = GetCurrentDir()

Import('asenv')
MODULES = asenv['MODULES']

objs = []

if('DCM' in MODULES):
    objs += Glob('Dcm/*.c')
    asenv.Append(CCFLAGS='-I%s/Dcm'%(cwd))
    asenv.Append(CCFLAGS='-DUSE_DCM')

if('DEM' in MODULES):
    objs += Glob('Dem/*.c')
    asenv.Append(CCFLAGS='-DUSE_DEM')

if('DET' in MODULES):
    objs += Glob('Det/*.c')
    asenv.Append(CCFLAGS='-DUSE_DET')

Return('objs')