import os
from building import *

cwd = GetCurrentDir()

Import('BOARD')
Import('asenv')
Import('MODULES')

objs = Glob('*.xml')
objs += Glob('*.arxml')

if('DCM' in MODULES):
    objs += Glob('Dcm/*.c')
    asenv.Append(CCFLAGS=' -I%s/Dcm -DUSE_DCM '%(cwd))


if('DET' in MODULES):
    objs += Glob('Det/*.c')
    asenv.Append(CCFLAGS=' -DUSE_DET ')

Return('objs')