import os
from building import *

cwd = GetCurrentDir()

Import('asenv')
ASROOT = asenv['ASROOT']

download = '%s/release/download'%(ASROOT)
lwip='%s/lwip'%(download)

if(not os.path.exists(lwip)):
    MKDir(download)
    RunCommand('''cd %s && git clone git://git.savannah.nongnu.org/lwip.git && 
        cd lwip && git checkout STABLE-1_4_1'''%(download))

MKSymlink(lwip,'%s/lwip'%(cwd))

objs = []

objs += Glob('lwip/src/api/*.c')
objs += Glob('lwip/src/core/*.c')
objs += Glob('lwip/src/core/ipv4/*.c')
objs += Glob('lwip/src/core/snmp/*.c')
objs += Glob('lwip/src/netif/*.c')
objs += Glob('lwip/src/netif/ppp/*.c')

asenv.Append(CPPPATH = ['%s/lwip/src/include'%(cwd)])
asenv.Append(CPPPATH = ['%s/lwip/src/include/ipv4'%(cwd)])
asenv.Append(CPPDEFINES = 'USE_LWIP')

if(os.getenv('LWIP_DEBUG')=='yes'):
    asenv.Append(CPPDEFINES = '-DLWIP_DEBUG=1')

Return('objs')
