import os
from building import *

cwd = GetCurrentDir()

Import('asenv')
arch = asenv['arch']

asenv.Append(CCFLAGS=' -I%s/include '%(cwd))
asenv.Append(CCFLAGS=' -I%s/kernel '%(cwd))
asenv.Append(CCFLAGS=' -I%s/portable/%s '%(cwd,arch))

objs = []

objs += Glob('kernel/*.c')
objs += Glob('portable/%s/*.c'%(arch))
objs += Glob('portable/%s/*.S'%(arch))

Return('objs')