import os
from building import *

cwd = GetCurrentDir()

Import('asenv')
arch = asenv['arch']

asenv.Append(CPPPATH=['%s/include'%(cwd)])
asenv.Append(CPPPATH=['%s/kernel'%(cwd)])
asenv.Append(CPPPATH=['%s/portable/%s'%(cwd,arch)])

objs = []

objs += Glob('kernel/*.c')
objs += Glob('portable/%s/*.c'%(arch))
objs += Glob('portable/%s/*.S'%(arch))

if(os.getenv('SCHED') == 'FIFO'):
    asenv.Append(CPPDEFINES='ENABLE_FIFO_SCHED')

Return('objs')