import os
from building import *

cwd = GetCurrentDir()

Import('asenv')
arch = asenv['arch']
ASROOT = asenv['ASROOT']
MODULES = asenv['MODULES']

download = '%s/release/download'%(ASROOT)
libelf='%s/libelf'%(download)

if(not os.path.exists(libelf)):
    MKDir(download)
    RunCommand('cd %s && git clone https://github.com/parai/libelf.git'%(download))

MKSymlink(libelf,'%s/libelf'%(cwd))

objs = []

objs += Glob('libelf/src/*.c')
objs += Glob('*.c')
objs += Glob('arch/%s/*.c'%(arch))

asenv.Append(CPPPATH = ['%s/libelf/include'%(cwd),cwd])
asenv.Append(CPPDEFINES = 'USE_LIBELF')

Return('objs')
